CREATE TABLE [dbo].[auditlog](
	[auditlog_id] [bigint] IDENTITY(1,1) NOT NULL,
	[auditlog_request_token] [varchar](500) NULL,
	[auditlog_request_url] [varchar](500) NULL,
	[auditlog_request_method] [varchar](100) NULL,
	[auditlog_request_query] [text] NULL,
	[auditlog_request_payload] [text] NULL,
	[auditlog_response_payload] [text] NULL,
	[auditlog_ip_address] [varchar](45) NULL,
	[auditlog_browser_useragent] [text] NULL,
	[auditlog_event_datetime] [datetime] NULL,
	[auditlog_event_actor] [int] NULL,
	[auditlog_event_actor_id] [uniqueidentifier] NULL,
	[auditlog_authorized] [tinyint] NULL,
	[auditlog_response_code] [int] NULL,
	[auditlog_created] [datetime] NULL,
	[created_at] [datetime] NULL,
	[updated_at] [datetime] NULL,
)
