create table Students(
	Id uniqueidentifier primary key default NEWId(),
	StudentId varchar(255) null,
	FirstName varchar(255) not null,
	MiddleName varchar(255) null,
	LastName varchar(255) null,
	DateOfBirth date null,
	FatherName varchar(255) null,
	MotherName varchar(255) null,
	Class int not null,
	AadharNumber bigint not null,
	Address varchar(max) not null,
	PinCode int not null,
	[UserName] [nchar](100) NOT NULL,
	[Password] [nchar](100) NOT NULL,
	[RoleId] [int] NOT NULL,
	[Email] [nchar](100) NOT NULL,
	[Phone] [nchar](10) NOT NULL,
	[SchoolId] [uniqueidentifier] NULL foreign key references Schools(Id),
	[TokenId] [bigint] NULL,
	CreatedBy uniqueidentifier null,
	CreatedDate datetime2(7) default getdate() NOT null,
	ModifiedBy uniqueidentifier null,
	ModifiedDate datetime2(7) null,
	DeletedBy uniqueidentifier null,
	DeletedDate datetime2(7) null,
	Status bit NOT null DEFAULT 1
)
